name: Deploy Assets to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload Artifact
        uses: actions/upload-artifact@v4 # Correct, current action
        with:
          name: assets # Give the artifact a name
          path: _assets

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact: assets # Use the correct artifact name
          config: |
            {
              "path": "/_assets"
            }
