name: Deploy Assets to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # This is the crucial line!
      pages: write # Required to deploy to Github Pages
      contents: read # Required to checkout the code

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Assets to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          path: _assets
          config: |
            {
              "path": "/_assets"
            }
