name: Deploy Assets to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List _assets contents
        run: ls -R _assets

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: |
            _assets/
            index.html

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: site         