name: Deploy Assets to GitHub Pages

on:
  push:
    branches:
      - main  # Or your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload Assets
        uses: actions/upload-pages-artifact@v2
        with:
          path: _assets

      - name: Deploy Assets to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          artifact: github-pages         
          config: |
            {
              "path": "/_assets"
            }
    
