name: Deploy Assets to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Assets to GitHub Pages
        uses: actions/deploy-pages@v2
        with:        
          path: _assets  
          # This configures the deployment to use the /_assets path.
          config: |
            {
              "path": "/_assets"
            }
