name: Deploy Assets to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload Assets as Artifact
        uses: actions/upload-pages-artifact@v2  # Correct action for Pages artifacts
        with:
          path: _assets

      - name: Deploy Assets to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          artifact: github-pages # Important: Specify the artifact name
          config: |
            {
              "path": "/_assets"
            }
